### ISSUE TITLE
Unescaped "$" an invalid character for passwords

### ISSUE THREAD

**Issue by nathan-nhm** [vinkla/shield#20]
Using the current hashing advice

> php -r "echo password_hash('my-secret-pa$sphr@se', PASSWORD_DEFAULT);"

Most special characters seem to work, allow authentication - but not a Dollar sign.

> php -r "echo password_hash('my-secret-pa\\$sphr@se', PASSWORD_DEFAULT);"

Does work, so this is a PHP issue - but it may be worth noting in documentation.

**Comment by vinkla** [comment]
Thanks for reporting! 

It seems it depends on if you generate the password using `$ php -r` or directly in your code. When I'm generating in the terminal using this following command:

```sh
$ php -r "echo password_hash('my-secret-pa$sphr@se', PASSWORD_DEFAULT);" | pbcopy
```

When I use the hashed password it returns `false`:

```php
$password = 'my-hashed-password';

echo password_verify('my-secret-pa$sphr@se', $password) ? 'true' : 'false';
```

If I hashed the password in the same script as where I verify it it returns `true`:

```php
$password = password_hash('my-secret-pa$sphr@se', PASSWORD_DEFAULT);

echo password_verify('my-secret-pa$sphr@se', $password) ? 'true' : 'false';
```

TBH I'm not really sure why it behaves this way. I've never had this issue myself and if anyone else has this issue in the future they can take a look at this issue.

**Comment by nathan-nhm** [comment]
Further research has showed it's probably Bash Special Parameters ( https://www.gnu.org/software/bash/manual/html_node/Special-Parameters.html ) that are sometimes being invoked, depending on the character following the `$`.

Swapping single and double quotes seems to perform as expected.
```
php -r 'echo password_hash("my-secret-pa$sphr@se", PASSWORD_DEFAULT);'
```
At least it's easier to recognize the PHP patterns than the Bash ones.

**Comment by vinkla** [comment]
Thanks for digging further @nathan-nhm! Would you mind sending a pull request changing the quotes?
