### ISSUE TITLE
Add. support to laravel 7

### ISSUE THREAD

**Issue by marcoax** [vinkla/shield#24]

**Comment by marcoax** [comment]
Please add support to Laravel 7

**Comment by vinkla** [comment]
https://github.com/vinkla/laravel-shield/blob/723c64c1c08351f4dbdda75ca5dee5d67abf5121/composer.json#L21

**Comment by marcoax** [comment]
Hi, seems dosen't  work on laravel 7 with  php 7.2

**Comment by SchwarzMartin** [comment]
Hi, doesn't work for me either. Using Laravel 7.3

**Comment by marcoax** [comment]
Hi the problem is due to php version


Il mar 31 mar 2020, 11:06 SchwarzMartin <notifications@github.com> ha
scritto:
