### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by reneroboter** [vinkla/shield#29]
The current version has no support for PHP 8.1. It would be nice if it got soon PHP 8.1 support :)

**Comment by reneroboter** [comment]
Ahh https://github.com/vinkla/laravel-shield/commit/c43978e0f9c04d6f1d585883f1e775310c696fd0 :)

**Comment by vinkla** [comment]
https://github.com/vinkla/laravel-shield/blob/c43978e0f9c04d6f1d585883f1e775310c696fd0/composer.json#L20
