### ISSUE TITLE
Only first user in the config file can logging

### ISSUE THREAD

**Issue by NicolasMahe** [vinkla/shield#3]
Hi,

When i add multiple users to the `users` array in `config/shield.php`, only the first of those users can logging.
If I change the order, still and only the first one can logging. The old first user can't logging anymore.

I protect my controller by adding to the constructor: `$this->middleware('shield');`
If I set a user as parameter of your middleware, I can connect with these user regardless of its position in the config's users array.

Here is my config file if it helps:

``` php
'users' => [
  'nico' => [
    '$2y$10$BgvuWx9opNNuXAhMn.2riOneZtCZuCeuweQnsPDim6hMiTV2mo0eK',
    '$2y$10$3vOU1uECBCIauy8KkwinoOLnOOB4M2FC51DC5NSo2b9PhY2QRDSle'
  ],
  'tom' => [
    '$2y$10$EAZF9FRE3Mvb3Ir24UY29uUHO7x4y05nlAbdb7u0HQcNBhbhX/kjC',
    '$2y$10$SRB/P3I3xu1e.vMISegVj.otRy9RIOqpc/bTlcQA9pNNtkRV5THBK'
  ],
],
```

I tried to determine the source of the problem without success.
I think it can only come from the `password_verify` function. All variables (`$username`, `$password` and `$credentials`) in the `validate` function are correct.

Do you successfully logging with any user when the config has multiple users ?

Thank you for the package and the help.

**Comment by vinkla** [comment]
Thanks a lot for filing this issue! It does sound like a bug. I'll take a look at it as soon as possible.

**Comment by vinkla** [comment]
Fixed now. Going to release a new version.
