### ISSUE TITLE
How to install with PHP 8 and Laravel 8

### ISSUE THREAD

**Issue by FrazeColder** [vinkla/shield#30]
Hey guys,

can anybody help me on how to install this package with composer and Laravel and PHP 8?

I already tried `composer require vinkla/shield:dev-master#4f78c3a23889543dbe23b5ccd47d9a44cdcfb7ff` without any success.

Kind regards

**Comment by vinkla** [comment]
Use the previous version.

**Comment by FrazeColder** [comment]
@vinkla can you please just tell me which line of `composer require` I have to use?

I get the same error when using my command above with the commit before `4f78c3a`
