### ISSUE TITLE
Add possibility to add an error message

### ISSUE THREAD

**Issue by Mad-dox** [vinkla/shield#31]
Hey,
Is it possible to change the error message without catching it via the Handler.php and overwriting it ?
I can see that you don't give any message when you throw the Unauthorized exception :

```php
if ($this->shield->verify($request->getUser(), $request->getPassword(), $user) === false) {
            throw new UnauthorizedHttpException('Basic');
}
```
Thanks for reading my message and have a good day !

**Comment by vinkla** [comment]
No, that is currently not supported. Its the default for basic auth. You can, as you say, extend and overwrite it.
