### ISSUE TITLE
Example of use

### ISSUE THREAD

**Issue by jaswdr** [vinkla/shield#5]
Hi,
I try to use this package but without sucess, can you explain how exactly can we use this ?

ps.: I try send a Authorization: Basic <hash> header, but the hash that is used is what ? user:password, user:hashed_password, other what ?

ty

**Comment by jaswdr** [comment]
seen the code I have success use making hash of the user and password and passing the hash in request

Example:

admin
php artisan shield:hash admin //$2y$10$N6XR/W9z7KD/SKFyDCbvdea/frOpUlsfOXUKc0GTfSN/vBBzp8qoe

With header

Authorization Basic <base64 of 2y$10$N6XR/W9z7KD/SKFyDCbvdea/frOpUlsfOXUKc0GTfSN/vBBzp8qoe:2y$10$N6XR/W9z7KD/SKFyDCbvdea/frOpUlsfOXUKc0GTfSN/vBBzp8qoe>

**Comment by vinkla** [comment]
Did you make it work?

**Comment by jaswdr** [comment]
Yes, everything ok, when using with Authorization HTTP Header I have pass the base64 encode of "hash_of_username:hash_of_password" instead of "username:password", and when using without this I need to pass the username + password

**Comment by vinkla** [comment]
Okay, good.
