### ISSUE TITLE
Shiled dosen't work on live server

### ISSUE THREAD

**Issue by reneroboter** [vinkla/shield#7]
I had the following problem, the login dosen' work if I enter the correct data, the login screen appears again and again. I check my login data, I changed my config file, however the problem isn't solved yet.

I used Shield in a Lumen project and everything ist working in my virtual machine ! 
The problem only appears on my server !

The virtual machine used Debian and the server Gentoo.

I also tried on different Browsers.

**Comment by vinkla** [comment]
Weird. Maybe you could use the same local environment in production?

**Comment by reneroboter** [comment]
I found the solution.
I checked phpinfo() on our Server and SERVER API was on CGI/FastCGI.

http://stackoverflow.com/questions/7053306/http-auth-via-php-php-auth-user-not-set?rq=1

**Comment by vinkla** [comment]
Great! Then I'll close this.

**Comment by reneroboter** [comment]
I added this into my public/.htaccess file and now it's work!
`SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0`

**Comment by vinkla** [comment]
Thanks for letting us know! Maybe someone else will have the same issue in the future.
