### ISSUE TITLE
get user or username from class?

### ISSUE THREAD

**Issue by jmp909** [vinkla/shield#8]
hi,

this is a great middleware thanks

I was wondering if it is possible to get the user or username in my code?

let's say i have

``` php
'User 1' => [
  '....hashed foo...', 
  '....hashed bar...', 
],
```

for `foo:bar`

is it possible for me to get `'User 1'` or `'foo'` in my code?

regards
Joe

**Comment by vinkla** [comment]
Yes, if you extend the `ShieldMiddleware` you can get the users name.

**Comment by jmp909** [comment]
I saw you can get $request->user and $request->password I think, but i wasn't sure about they actual key used in the config. ('User 1' above)

thanks
j

**Comment by vinkla** [comment]
Did you solve it?
