### ISSUE TITLE
action on login dialog cancel?

### ISSUE THREAD

**Issue by jmp909** [vinkla/shield#9]
Hi

is it possible to redirect the user (or some other action) if the user cancels the auth dialog? currently it throws the usual "Whoops" error. (UnauthorizedHttpException in ShieldMiddleware.php)

I tried catching the `\Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException` in `app\Exceptions\Handler.php` but what happens is that it always performs the action afterwards Even if I try and force the login dialog again (by going into http://wrong:password@) , the login dialog won't appear again.

eg if I handle this exception, I can't try login again as it'll always show the 503 page.

``` php
public function render($request, Exception $e) {
  if ($e instanceof \Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException) {
    return response()->view('errors.503', [], 503);
  }
```

thanks
J

**Comment by jmp909** [comment]
Hi,

I've partly worked out the problem .. for an error page, I needed to add the `WWW-Authenticate' => 'Basic'` header

``` php
    public function render($request, Exception $e)
    {

        if ($e instanceof \Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException) {

            // need to add this header so that basic auth is triggered again on refresh
            $headers = array('WWW-Authenticate' => 'Basic');

            return response()->view('errors.401', [], 401, $headers);
        }

        return parent::render($request, $e);
```

but for a redirect that doesn't seem to work. unless I am calling the redirect incorrectly

thanks
J

**Comment by vinkla** [comment]
If you need to be able to redirect the user you must check how many times they've tried to login with maybe sessions. Since the browsers needs to get the 401 header back in order to display the view there is no way around this. You could store an integer which you +1 everytime the login fails and then before the 401 is being thrown you check how many times they've tried to login.

**Comment by jmp909** [comment]
thanks. that's useful to know. I'll stick with the error page for now!

regards
J
